### ISSUE TITLE
Long processing time

### ISSUE THREAD

**Issue by Bramvdhout** [CLARIAH/COW#112]
The transformation process of a large dataset can take up a looong time (ANDB dataset >2 hours). 

_This issue is extracted from Issue #108 opened by @MiconSchorsij_

**Comment by Bramvdhout** [comment]
Surprisingly, COW is pretty darn fast when it comes to handling large datasets. But large datasets, containing a large number of transformations, will just take a lot of processing time. Especially on user-computers. We recommend running COW on a server to speed up this process.

**Comment by MiconSchorsij** [comment]
Question: how can I use CoW on a server? I would like to try that.

**Comment by rlzijdeman** [comment]
Not sure how you useful this is, but the shopping list would be:
- buy a server or get some server space (e.g. via amazon);
- install python3 if not already
- get going with cow! see this new [quick tutorial](https://github.com/clariah/cow_tutorial)
