### ISSUE TITLE
Update to RDFlib 6.0.0

### ISSUE THREAD

**Issue by nicholascar** [CLARIAH/COW#119]
Hi COW people, Nick, maintainer of RDFlib here. Could you please update COW to use RDFlib 6.0.0? It incorporates the rdflib-jsonld plugin too, so you can drop that dependency also.

**Comment by wxwilcke** [comment]
Hi, Nicholas,

Thanks for pointing this out. I've updated RDFlib and all other dependencies.

- Xander

**Comment by nicholascar** [comment]
You can remove rdflib-jsonld as all of that’s package’s content is in rdflib now.

**Comment by wxwilcke** [comment]
> You can remove rdflib-jsonld as all of that’s package’s content is in rdflib now.

Ah, I missed that in your original post. I've removed that dependency, thanks.
