### ISSUE TITLE
UserWarning: Code: linkURI is not defined in namespace XSD

### ISSUE THREAD

**Issue by Thunnisvanoort** [CLARIAH/COW#122]
Last week I received the following error message:

C:\Users\U623174\AppData\Local\Programs\Python\Python310\lib\site-packages\cow_csvw\converter\csvw.py:599: UserWarning: Code: linkURI is not defined in namespace XSD
  if URIRef(csvw_datatype) == XSD.linkURI:

It is probably related to the following part of the json (see attachment), but I am not certain:

   {
    "@id": "https://www.ru.nl/slavenregisters/WR46-220113TST.csv/column/godsd_db",
    "name": "godsd_db",
    "titles": [
     "religion in dbpedia"
    ],
    "dc:description": "Dbpedia description of the stated religious affiliation",
    "datatype": "xsd:linkURI",
    "aboutUrl": "person/{ID}"
   },

[WR46-220113TST.csv-metadata - 20220224.txt](https://github.com/CLARIAH/COW/files/8131638/WR46-220113TST.csv-metadata.-.20220224.txt)

**Comment by wxwilcke** [comment]
Hi @Thunnisvanoort,

The datatype `linkURI` does not exist in the XSD namespace [1]. You can use another datatype that is defined in XSD, provided it fits the purpose, or search for one from a different vocabulary.

Best,
Xander 

[1] https://www.w3.org/TR/xmlschema11-2/#built-in-datatypes
