### ISSUE TITLE
wrong warning?

### ISSUE THREAD

**Issue by rlzijdeman** [CLARIAH/COW#21]
Hi, I just 'build' a file with the converter, but don't think the warning I received is appropriate?

```
Building schema for /.../git/sdh-public-datasets/clio-infra/geocoder_cshapes.csv
Detected encoding: ascii (1.0 confidence)
Detected dialect: csv.dialect (delimiter: ',')
Delimiter is: ,
Found headers: [u'Webmapper code', u'Webmapper numeric code', u'ccode', u'code parent', u'country', u'country name', u'ctr', u'start year', u'end year']
WARNING: You have two or more column headers that are syntactically the same. Conversion might 
produce incorrect results because of conflated URIs or worse
Done
```

**Comment by rlzijdeman** [comment]
Hi, I checked whether this is the result of spaces in the column headers, but it is not.

**Comment by rijpma** [comment]
I think this fixes the warning but the conversion still fails.

**Comment by rlzijdeman** [comment]
+1 @rijpma

**Comment by rlzijdeman** [comment]
So to sum up a discussion on datalegend's Slack:
- the issue at hand appears to lie in the fact that **the base url defined in @base is not parsed as part of the aboutUrl when using COW to convert**;
- manually overriding the baseUrl with `""` in the prefix specification does not alter this;
- using a combination of a prefix with `{_row}` does not work either (e.g. `hsn:{_row}`;
- a **quick fix** is to explicate the baseUrl like so: `"aboutUrl": "http://example.org/resource/{_row}",

**Comment by rijpma** [comment]
valueUrls using references to columns (i.e. {variable}) also fail.

Maybe this should be a separate issue though as the false warning does not seem to be related.

**Comment by rlzijdeman** [comment]
right, warning is fixed but issue with @base and valueUrls are not. closing this issue and creating seperate issues for those.
