### ISSUE TITLE
permission issue during install

### ISSUE THREAD

**Issue by rlzijdeman** [CLARIAH/COW#25]
Hi, I run into a permission issue of some sort. Please find the output below:

`pip install cow_csvw
Collecting cow_csvw
  Downloading cow_csvw-0.11.tar.gz (6.7MB)
    100% |████████████████████████████████| 6.7MB 216kB/s
Requirement already satisfied: alabaster==0.7.9 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: appdirs==1.4.3 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: argh==0.26.2 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: Babel==2.3.4 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: backports-abc==0.5 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: beautifulsoup4==4.4.1 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Collecting certifi==2016.9.26 (from cow_csvw)
  Using cached certifi-2016.9.26-py2.py3-none-any.whl
Requirement already satisfied: chardet==2.3.0 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: docutils==0.12 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: html5lib==0.999999999 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: imagesize==0.7.1 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: iribaker==0.1.2 in /Users/RichardZ/git/wp4-converters/src/iribaker (from cow_csvw)
Requirement already satisfied: isodate==0.5.4 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: Jinja2==2.8 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: Js2Py==0.31 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: keepalive==0.5 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: language-tags==0.4.1 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: livereload==2.5.0 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: MarkupSafe==0.23 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: nose==1.3.7 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: nosetests-json-extended==0.1.0 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Collecting numpy==1.11.2 (from cow_csvw)
  Using cached numpy-1.11.2-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Requirement already satisfied: packaging==16.8 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Collecting pandas==0.19.1 (from cow_csvw)
  Using cached pandas-0.19.1-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Requirement already satisfied: pathtools==0.1.2 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: port-for==0.3.1 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Collecting Pygments==2.1.3 (from cow_csvw)
  Using cached Pygments-2.1.3-py2.py3-none-any.whl
Collecting pyparsing==2.2.0 (from cow_csvw)
  Using cached pyparsing-2.2.0-py2.py3-none-any.whl
Requirement already satisfied: python-dateutil==2.6.0 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: pytz==2015.7 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: PyYAML==3.11 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Collecting rdflib==4.2.2 (from cow_csvw)
Requirement already satisfied: rdflib-jsonld==0.4.0 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: regex==2015.6.24 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: requests==2.8.1 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: rfc3987==1.3.4 in /usr/local/lib/python2.7/site-packages/rfc3987-1.3.4-py2.7.egg (from cow_csvw)
Requirement already satisfied: simplejson==3.8.1 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: singledispatch==3.4.0.3 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: six==1.10.0 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: snowballstemmer==1.2.1 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: SPARQLWrapper==1.7.6 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: Sphinx==1.4.8 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: sphinx-autobuild==0.6.0 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Collecting tornado==4.4.2 (from cow_csvw)
Collecting travis==0.0.2 (from cow_csvw)
  Using cached travis-0.0.2-py2.py3-none-any.whl
Requirement already satisfied: tzlocal==1.2 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: unicodecsv==0.14.1 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: uritemplate==0.6 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: watchdog==0.8.3 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: webencodings==0.5 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: Werkzeug==0.11.2 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Collecting xlrd==1.0.0 (from cow_csvw)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python2.7/site-packages (from html5lib==0.999999999->cow_csvw)
Building wheels for collected packages: cow-csvw
  Running setup.py bdist_wheel for cow-csvw ... error
  Complete output from command /usr/local/opt/python/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/p0/jvvv0sd91kx77mgq3sn0_4xr0000gp/T/pip-build-VbiU1G/cow-csvw/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/p0/jvvv0sd91kx77mgq3sn0_4xr0000gp/T/tmpJWwRY9pip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/cow_csvw
  copying src/__init__.py -> build/lib/cow_csvw
  copying src/config.py -> build/lib/cow_csvw
  copying src/cow_tool.py -> build/lib/cow_csvw
  copying src/csv2qb.py -> build/lib/cow_csvw
  copying src/csv2qber-schema.py -> build/lib/cow_csvw
  copying src/csvw_tool.py -> build/lib/cow_csvw
  copying src/../../../../../../../../../installer.failurerequests -> build/lib/cow_csvw/../../../../../../../../..
  error: [Errno 13] Permission denied: 'build/lib/cow_csvw/../../../../../../../../../installer.failurerequests'

  ----------------------------------------
  Failed building wheel for cow-csvw
  Running setup.py clean for cow-csvw
Failed to build cow-csvw
Installing collected packages: certifi, numpy, pandas, Pygments, pyparsing, rdflib, tornado, travis, xlrd, cow-csvw
  Found existing installation: certifi 2017.4.17
    Uninstalling certifi-2017.4.17:
      Successfully uninstalled certifi-2017.4.17
  Found existing installation: numpy 1.9.2
    Uninstalling numpy-1.9.2:
      Successfully uninstalled numpy-1.9.2
  Found existing installation: pandas 0.16.2
    Uninstalling pandas-0.16.2:
      Successfully uninstalled pandas-0.16.2
  Found existing installation: Pygments 2.2.0
    Uninstalling Pygments-2.2.0:
      Successfully uninstalled Pygments-2.2.0
  Found existing installation: pyparsing 2.1.8
    Uninstalling pyparsing-2.1.8:
      Successfully uninstalled pyparsing-2.1.8
  Found existing installation: rdflib 4.2.1
    Uninstalling rdflib-4.2.1:
      Successfully uninstalled rdflib-4.2.1
  Found existing installation: tornado 4.5.1
    Uninstalling tornado-4.5.1:
      Successfully uninstalled tornado-4.5.1
  Found existing installation: xlrd 0.9.4
    Uninstalling xlrd-0.9.4:
      Successfully uninstalled xlrd-0.9.4
  Running setup.py install for cow-csvw ... error
    Complete output from command /usr/local/opt/python/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/p0/jvvv0sd91kx77mgq3sn0_4xr0000gp/T/pip-build-VbiU1G/cow-csvw/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/p0/jvvv0sd91kx77mgq3sn0_4xr0000gp/T/pip-3WlA72-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/cow_csvw
    copying src/__init__.py -> build/lib/cow_csvw
    copying src/config.py -> build/lib/cow_csvw
    copying src/cow_tool.py -> build/lib/cow_csvw
    copying src/csv2qb.py -> build/lib/cow_csvw
    copying src/csv2qber-schema.py -> build/lib/cow_csvw
    copying src/csvw_tool.py -> build/lib/cow_csvw
    copying src/../../../../../../../../../installer.failurerequests -> build/lib/cow_csvw/../../../../../../../../..
    error: [Errno 13] Permission denied: 'build/lib/cow_csvw/../../../../../../../../../installer.failurerequests'

    ----------------------------------------
Command "/usr/local/opt/python/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/p0/jvvv0sd91kx77mgq3sn0_4xr0000gp/T/pip-build-VbiU1G/cow-csvw/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/p0/jvvv0sd91kx77mgq3sn0_4xr0000gp/T/pip-3WlA72-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/p0/jvvv0sd91kx77mgq3sn0_4xr0000gp/T/pip-build-VbiU1G/cow-csvw/`

**Comment by rlzijdeman** [comment]
Hi, using sudo fixes it. Please note the first lines:

administrators-MacBook-Pro-3:cow RichardZ$ sudo pip install cow_csvw
Password:
The directory '/Users/RichardZ/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/RichardZ/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting cow_csvw
  Downloading cow_csvw-0.11.tar.gz (6.7MB)
    100% |████████████████████████████████| 6.7MB 233kB/s
Requirement already satisfied: alabaster==0.7.9 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: appdirs==1.4.3 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: argh==0.26.2 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: Babel==2.3.4 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: backports-abc==0.5 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: beautifulsoup4==4.4.1 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: certifi==2016.9.26 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: chardet==2.3.0 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: docutils==0.12 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: html5lib==0.999999999 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: imagesize==0.7.1 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: iribaker==0.1.2 in /Users/RichardZ/git/wp4-converters/src/iribaker (from cow_csvw)
Requirement already satisfied: isodate==0.5.4 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: Jinja2==2.8 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: Js2Py==0.31 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: keepalive==0.5 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: language-tags==0.4.1 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: livereload==2.5.0 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: MarkupSafe==0.23 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: nose==1.3.7 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: nosetests-json-extended==0.1.0 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: numpy==1.11.2 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: packaging==16.8 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: pandas==0.19.1 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: pathtools==0.1.2 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: port-for==0.3.1 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: Pygments==2.1.3 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: pyparsing==2.2.0 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: python-dateutil==2.6.0 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: pytz==2015.7 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: PyYAML==3.11 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: rdflib==4.2.2 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: rdflib-jsonld==0.4.0 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: regex==2015.6.24 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: requests==2.8.1 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: rfc3987==1.3.4 in /usr/local/lib/python2.7/site-packages/rfc3987-1.3.4-py2.7.egg (from cow_csvw)
Requirement already satisfied: simplejson==3.8.1 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: singledispatch==3.4.0.3 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: six==1.10.0 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: snowballstemmer==1.2.1 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: SPARQLWrapper==1.7.6 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: Sphinx==1.4.8 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: sphinx-autobuild==0.6.0 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: tornado==4.4.2 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: travis==0.0.2 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: tzlocal==1.2 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: unicodecsv==0.14.1 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: uritemplate==0.6 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: watchdog==0.8.3 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: webencodings==0.5 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: Werkzeug==0.11.2 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: xlrd==1.0.0 in /usr/local/lib/python2.7/site-packages (from cow_csvw)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python2.7/site-packages (from html5lib==0.999999999->cow_csvw)
Installing collected packages: cow-csvw
  Running setup.py install for cow-csvw ... done
Successfully installed cow-csvw-0.11

**Comment by bencomp** [comment]
I'm having the same issue, even when installing in a fresh `virtualenv`. Because it is a virtualenv, you shouldn't have to use sudo.

**Comment by bencomp** [comment]
Apparently the issue is specific to installing the `cow-csvw` package itself, as installing all the dependencies worked fine in the virtualenv.

```
m0022105:~ companjenba$ virtualenv virtualenvs/cow
New python executable in /Users/companjenba/virtualenvs/cow/bin/python2.7
Also creating executable in /Users/companjenba/virtualenvs/cow/bin/python
Installing setuptools, pip, wheel...done.
m0022105:~ companjenba$ source virtualenvs/cow/bin/activate
(cow) m0022105:~ companjenba$ pip install cow-csvw
Collecting cow-csvw
  Using cached cow_csvw-0.26.tar.gz
Collecting alabaster==0.7.9 (from cow-csvw)
  Using cached alabaster-0.7.9-py2.py3-none-any.whl
[....]
Requirement already satisfied: setuptools>=18.5 in ./virtualenvs/cow/lib/python2.7/site-packages (from html5lib==0.999999999->cow-csvw)
```

So the required packages have been installed, only `cow-csvw` itself needs to be built and installed:

```
Building wheels for collected packages: cow-csvw
  Running setup.py bdist_wheel for cow-csvw ... error
  Complete output from command /Users/companjenba/virtualenvs/cow/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/mw/cyflttp13qb25jvyqqhn74qwljlstg/T/pip-build-aCEswj/cow-csvw/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/mw/cyflttp13qb25jvyqqhn74qwljlstg/T/tmpBXRRxBpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/cow_csvw
  copying src/__init__.py -> build/lib/cow_csvw
  copying src/config.py -> build/lib/cow_csvw
  copying src/csv2qb.py -> build/lib/cow_csvw
  copying src/csv2qber-schema.py -> build/lib/cow_csvw
  copying src/csvw_tool.py -> build/lib/cow_csvw
  copying src/../../../../../../../../../installer.failurerequests -> build/lib/cow_csvw/../../../../../../../../..
  error: [Errno 13] Permission denied: 'build/lib/cow_csvw/../../../../../../../../../installer.failurerequests'
  
  ----------------------------------------
  Failed building wheel for cow-csvw
  Running setup.py clean for cow-csvw
Failed to build cow-csvw
Installing collected packages: alabaster, appdirs, argh, pytz, Babel, backports-abc, beautifulsoup4, certifi, chardet, docutils, six, webencodings, html5lib, imagesize, rfc3987, iribaker, isodate, MarkupSafe, Jinja2, tzlocal, Js2Py, keepalive, language-tags, singledispatch, tornado, livereload, nose, nosetests-json-extended, numpy, pyparsing, packaging, python-dateutil, pandas, pathtools, port-for, Pygments, PyYAML, rdflib, rdflib-jsonld, regex, requests, simplejson, snowballstemmer, SPARQLWrapper, Sphinx, watchdog, sphinx-autobuild, travis, unicodecsv, uritemplate, Werkzeug, xlrd, cow-csvw
  Running setup.py install for cow-csvw ... error
    Complete output from command /Users/companjenba/virtualenvs/cow/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/mw/cyflttp13qb25jvyqqhn74qwljlstg/T/pip-build-aCEswj/cow-csvw/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/mw/cyflttp13qb25jvyqqhn74qwljlstg/T/pip-WazIRB-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/companjenba/virtualenvs/cow/bin/../include/site/python2.7/cow-csvw:
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/cow_csvw
    copying src/__init__.py -> build/lib/cow_csvw
    copying src/config.py -> build/lib/cow_csvw
    copying src/csv2qb.py -> build/lib/cow_csvw
    copying src/csv2qber-schema.py -> build/lib/cow_csvw
    copying src/csvw_tool.py -> build/lib/cow_csvw
    copying src/../../../../../../../../../installer.failurerequests -> build/lib/cow_csvw/../../../../../../../../..
    error: [Errno 13] Permission denied: 'build/lib/cow_csvw/../../../../../../../../../installer.failurerequests'
    
    ----------------------------------------
Command "/Users/companjenba/virtualenvs/cow/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/mw/cyflttp13qb25jvyqqhn74qwljlstg/T/pip-build-aCEswj/cow-csvw/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/mw/cyflttp13qb25jvyqqhn74qwljlstg/T/pip-WazIRB-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/companjenba/virtualenvs/cow/bin/../include/site/python2.7/cow-csvw" failed with error code 1 in /private/var/folders/mw/cyflttp13qb25jvyqqhn74qwljlstg/T/pip-build-aCEswj/cow-csvw/
```

I then realised that the [installation instructions]() never said anything about installing the package itself, but using the source directly. So I `cd`'ed into the checked out and updated git repository and called the `csvw-tool.py`:

```
(cow) m0022105:~ companjenba$ cd git/COW/
(cow) m0022105:COW companjenba$ python cow/csvw-tool.py 
usage: csvw-tool.py [-h] [--dataset DATASET] [--delimiter DELIMITER]
                    [--quotechar QUOTECHAR] [--processes PROCESSES]
                    [--chunksize CHUNKSIZE] [--base BASE]
                    {convert,build} file [file ...]
csvw-tool.py: error: too few arguments
```

Could you fix the packaging so that `pip install` in a virtualenv actually installs the package inside the virtualenv?
