### ISSUE TITLE
use of csvw:{foobar} generats error in metadata graphs

### ISSUE THREAD

**Issue by rlzijdeman** [CLARIAH/COW#33]
For example:

356343 _:N8553915f2a8243e9a776ce4f391fc305 <http://www.w3.org/ns/csvw#lang> "{{lang_code|lower}}" <http://iisg.amsterdam/occupation_link/provenance/bf682913/2017-11-03T22:19> .

@albertmeronyo is this maybe linked to #12 ?

**Comment by rijpma** [comment]
Did you use `{{lang_code|lower}}` in the json file? If so, it should probably be `{{lang_code|lower()}}` to work.

**Comment by rlzijdeman** [comment]
Hi, I tried both, to no avail. NB: this only concerns the conversion csvw:value in the nano-pub part.

**Comment by rlzijdeman** [comment]
Apparently, this is just 'ugly' representation of how the csvw:value was created. No error, but ugly.
