### ISSUE TITLE
Unicode encode error

### ISSUE THREAD

**Issue by Bramvdhout** [CLARIAH/COW#34]
While building database in COW, received following error re: codec. Understood that CSV was set to UTF-8, and needed to be in ASCII. However, might need some extra explanation in error message for non-tech users.

```
  File "C:\Datalegend\Clone\COW\cow\converter\csvw.py", line 109, in build_schema
    "@id": iribaker.to_iri("{}/{}/column/{}".format(base, url, head)),
UnicodeEncodeError: 'ascii' codec can't encode character u'\ufeff' in position 0: ordinal not in range(128)
```

**Comment by melvinroest** [comment]
Closing this issue as encoding errors shouldn't happen in the first place. When they do happen, they should be reported as issues. If encoding issues keep persisting, then perhaps more user-friendly logging would be necessary.
