### ISSUE TITLE
Error code during Conversion

### ISSUE THREAD

**Issue by Bramvdhout** [CLARIAH/COW#35]
After converting in Windows, CMD prints the following error code hundreds of times.
![image](https://user-images.githubusercontent.com/32885158/32663586-c5058af4-c62e-11e7-9f9e-4cbb62bfefda.png)

**Comment by RubenSchalk** [comment]
I had the same issue, but it disappeared after I assigned only 1 process when converting (simply add --processes 1 to command line). It's not an ideal solution for large files of course...

**Comment by Bramvdhout** [comment]
Doesn't appear to be working, I'm afraid.

**Convert with --processes 1**
```
C:\Datalegend\Clone\COW\cow>python csvw-tool.py convert C:\Datalegend\Proef\gruber_mosaic_CGOTHO_version5-UTF.csv --processes 1
Converting C:\Datalegend\Proef\gruber_mosaic_CGOTHO_version5-UTF.csv to RDF
Initializing converter for C:\Datalegend\Proef\gruber_mosaic_CGOTHO_version5-UTF.csv
Processes: 1
Chunksize: 5000
No handlers could be found for logger "rdflib.term"
Quotechar: '"'
Delimiter: ','
Encoding : 'utf-8'
Taking encoding, quotechar and delimiter specifications into account...
Starting conversion
Opening CSV file for reading
Starting in a single process
Row: 0
... done
Something went wrong, skipping C:\Datalegend\Proef\gruber_mosaic_CGOTHO_version5-UTF.csv.
```

**Convert with –processes 1 AND removing json**
```
C:\Datalegend\Clone\COW\cow>python csvw-tool.py convert C:\Datalegend\Proef\gruber_mosaic_CGOTHO_version5-UTF.csv --processes 1
Converting C:\Datalegend\Proef\gruber_mosaic_CGOTHO_version5-UTF.csv to RDF
Initializing converter for C:\Datalegend\Proef\gruber_mosaic_CGOTHO_version5-UTF.csv
Something went wrong, skipping C:\Datalegend\Proef\gruber_mosaic_CGOTHO_version5-UTF.csv.
```

**Comment by albertmeronyo** [comment]
Hi @Bramvdhout 
Could you try to convert using the online version of COW at http://cattle.datalegend.net/ and let me know if the issue persists?

Thanks!

**Comment by Bramvdhout** [comment]
It worked flawlessly!
I used the original file, the one that used to give encoding errors, to build and then to convert. Everything seems to work!

**Comment by albertmeronyo** [comment]
Thanks for letting me know! 
I'm leaving the issue open (since it's relevant for command-line Windows users) but mark as low-priority.

**Comment by melvinroest** [comment]
Closing this as this is a Python 2 issue.
