### ISSUE TITLE
New COW version error after build

### ISSUE THREAD

**Issue by Bramvdhout** [CLARIAH/COW#37]
New version of COW: build results in the following error message.

![image](https://user-images.githubusercontent.com/32885158/33083781-92386fd2-cee0-11e7-997f-6b9dca2ec642.png)

**Comment by rijpma** [comment]
This might be related to the cow's attempt to backup and rename the old metdata file going wrong on windows. Could you manually remove the old gruber...utf.csv-metadata.json file and see what happens?

**Comment by Bramvdhout** [comment]
Removing old json file, and then converting results in old bug reported in Issue #35.
Tried with fresh Gruber_mosaic file (saved in Sublime 3 with UTF-8 encoding) but same error and empty nq-file.
Removed COW, reinstalled according to the tutorial to rule out any problems there, same problem.

**Comment by albertmeronyo** [comment]
Hi @Bramvdhout 
Could you try to convert using the online version of COW at http://cattle.datalegend.net/ and let me know if the issue persists?

Thanks!

**Comment by melvinroest** [comment]
I was able to reproduce this issue. The work around perfoms as expected, so: remove the metadata.json file and run the build and (later on) the convert step and you should get a `.nq` file.
