### ISSUE TITLE
Cattle: 502 Bad Gateway on conversion.

### ISSUE THREAD

**Issue by Bramvdhout** [CLARIAH/COW#38]
Tried converting a csv file with Cattle, received a `502 Bad Gateway`, reduced the file-size by taking out rows and converted without issue. 

File that timed-out was 200kb with 3222 rows and 9 columns.
File that worked was 44kb with 749 rows and 9 columns.

**Comment by albertmeronyo** [comment]
This is being addressed now by the improved error reporting and the druid connection, so I'm closing the issue
