### ISSUE TITLE
specify valueUrl without propertyUrl

### ISSUE THREAD

**Issue by rijpma** [CLARIAH/COW#39]
Currently if you want to specify a valueUrl, you have to provide a propertyUrl as well. If not, you get the following error:

```
Exception: Cannot convert `None` to valid IRI
The argument you provided does not comply with RFC 3987 and is not parseable as a IRI(there is no scheme or no net location part)
```

Example json for the test.csv file

```
   {
    "titles": [
     "Country"
    ], 
    "@id": "https://iisg.amsterdam/resource/test.csv/column/Country", 
    "name": "Country", 
    "dc:description": "Country",
    "valueUrl": "clioctr:{Country}"
   }, 
```

COW should either convert this or specify in the error message that it cannot make valueUrls unless propertyUrl is specified.

**Comment by rlzijdeman** [comment]
Tested this and in both 'regular' columns and 'virtual' columns this works. In the virtual column case you will end up with `<https://iisg.amsterdam/vocab/None>`.
