### ISSUE TITLE
Converting with invalid AboutURL

### ISSUE THREAD

**Issue by Bramvdhout** [CLARIAH/COW#41]
During the workshop, a user asked what happened if you changed to AboutURL into a non-existing heading. The presentation decided to move on, but I wanted to try it out.
The provided example was what if user typed 
`"aboutUrl": "country/{Countries}"`
When it should be
`"aboutUrl": "country/{Country}"` 

the resulting NQ results in:
`<https://iisg.amsterdam/resource/country/_Countries_> <https://iisg.amsterdam/resource/Rank> "5"^^<http://www.w3.org/2001/XMLSchema#string> <http://iisg.amsterdam/imf_gdppc/assertion/de48f611/2018-02-23T11:04> .`

Note the underscore before and after Countries. Is this a problem? And if so, can COW check if the Column exists in the CSV file?

**Comment by rlzijdeman** [comment]
Hi,  I don't think this is a problem, because it will be apparent that in addition to a wrong uri, there's only one triple describing _Countries_, whereas you would have expected multiple triples with country values in the position.
