### ISSUE TITLE
provenance examples in wiki

### ISSUE THREAD

**Issue by rlzijdeman** [CLARIAH/COW#47]
@RubenSchalk says:
do we want to add a section on provenance? If so, we should probably think of a way to try and standardize that as well in the json template

**Comment by melvinroest** [comment]
@rlzijdeman: it seems this issue is resolved? I see a provenance chapter in the wiki that was edited on Oct 22, 2018 and you self-assigned it on Oct 18, 2018. I'm closing this issue for now, if you think there's more to be done you can reopen it.
