### ISSUE TITLE
COW Wiki Home Page Suggestion

### ISSUE THREAD

**Issue by Bramvdhout** [CLARIAH/COW#48]
Some terms and/or processes that we see as obvious, might need an extra step of explanation for beginners. 
_Visual_
More space between (or even a dividing line) between the two columns, to create a more recognisable separation of the two. If it looks like a table, it might be more understandable.

_More verbose_
In the end, the wiki doesn't really use the above mentioned data other than the top row (buurt-a). However, it's easier to understand/distinguish adjustments if the used variables are more unique. Maybe use the real names of Amsterdam neighbourhoods? Again, it's not much of an issue now because the other rows aren't used, but one less dash in a triple wouldn't hurt.

**Comment by rlzijdeman** [comment]
hi @Bramvdhout,

I've made a more visual 'table' as much as github markdown allows me too (the line seperator command doesn't seem to work).

Much to your surprise neighbourhoods in the 19th century and beyond were actually referred to as 'A', 'B', etc. Now that doesn't take away the point about the hyphen. I have therefore added a paragraph in wiki/home on who we believe is able to use this tool. (E.g. if you get scared of hyphens, this might not be for you). Basically, I said that with a BA in history and some perseverance, you should be able to manage.
