### ISSUE TITLE
Jinja template does not work if a slash, or space (special character) is in variable name

### ISSUE THREAD

**Issue by Bramvdhout** [CLARIAH/COW#53]
While converting a json file which has a slash `/` in the variable name, the Jinja template does not work.

For example
`"csvw:value": "{{properties/name_in_file|replace(',', '.')}}"`

would not apply the Jinja.

**Comment by rijpma** [comment]
Might automatically get substituted by an underscore

**Comment by melvinroest** [comment]
@Bramvdhout and @rijpma 
is it possible to give a minimal `.csv` and `metadata.json` example for this? I don't know how to reproduce this.

**Comment by RubenSchalk** [comment]
See attached zip for an example. The variable VALIDchildren&MS breaks the conversion due to the Jinja templating there. However, I'm not sure if this issue is a priority (people should avoid special characters in variable names IMHO).

[tafelVbis.zip](https://github.com/CLARIAH/COW/files/5369948/tafelVbis.zip)

**Comment by melvinroest** [comment]
I read the issue too quickly. Variable names should not have special characters. Every programming language that I've used has this rule, this includes templating languages like Jinja.

The rules are as follows: 
1. Your first character has to be a small letter, or capital letter, or an underscore `_`.
2. The second character and onwards can be a digit as well, on top of the previous options.

Source: https://stackoverflow.com/questions/17687534/jinja2-variables-naming-are-variables-naming-restrictions-the-same-as-for-pyth
