### ISSUE TITLE
update cattle with latest CoW

### ISSUE THREAD

**Issue by rlzijdeman** [CLARIAH/COW#56]
Hi @RoderickvanderWeerdt,

I've fixed the dcterms issue that @rijpma mentioned earlier. Would you please update the cattle service with the latest version on github?

@albertmeronyo knows how to do this, or might ask you to write a webhook for it 😆

**Comment by RoderickvanderWeerdt** [comment]
Albert has taken care of it, no hooks required. ;)

**Comment by albertmeronyo** [comment]
Done!
