### ISSUE TITLE
wrong reference to datalegend.org

### ISSUE THREAD

**Issue by rlzijdeman** [CLARIAH/COW#58]
Hi, when converting the basic file, the first triple reads:

`_:Nd9e34d6863f14119b0e3393ba3a8a75e <http://schema.org/url> <http://datalegend.org/> <https://iisg.amsterdamimf_gdppc/provenance/0f8040d8/2018-04-30T18:17> .
`
Here, 'datalegend.org' should read 'datalegend.net'

AND

there should be a slash between the base URI and file name:
`<https://iisg.amsterdam/imf_gdppc/provenance/0f8040d8/2018-04-30T18:17>`
(slash after amsterdam)

**Comment by RoderickvanderWeerdt** [comment]
As with #57 this should be solved by the combination of the folders (#60), as the newer version (maybe?) in the cow folder has the first problem solved by changing org into net on line 81. The second problem should be solved by changed the namespace.
