### ISSUE TITLE
AE-character kills the cow

### ISSUE THREAD

**Issue by rlzijdeman** [CLARIAH/COW#64]
Hi,

A colon-separated csv contains this value in a given row:
``` mr. Æ.baron van Mackay```

- Uploading the CSV in COW results in an error.
- Removing the row containing the special character fixes the problem
- Opening the file in OpenOffice and saving as UTF-8 fixes the problem

Is it possible to make the last step automagical? Or someother way to circumvent this issue?

Best,

Richard

**Comment by rijpma** [comment]
COW tells you what encoding it thinks the file is, right? What encoding is it and does it match the actual encoding of the file? 

If the answer to the final question is "no", this might be difficult to fix. Something to consider is giving csvw_tool an "--encoding" argument that would force the correct encoding.

Final thought: does cow work in python3? I've fixed encoding nightmares before by switching pythons

**Comment by RoderickvanderWeerdt** [comment]
You are right, cow does sniff out the encoding and the new version of cow (as released to pipy this morning) uses this encoding to correctly handle the file.

In python3 this would have been a bit easier, but currently cow is still written in python2.7, so it required an additional import.

The new version of Cow is also being used by cattle as of today, so the Æ character (or any other special character) should not be a problem anymore.
