### ISSUE TITLE
install 'error'

### ISSUE THREAD

**Issue by rlzijdeman** [CLARIAH/COW#65]
Hi, @RoderickvanderWeerdt  when installing CoW on macosx 10.14.1 and Linux Ubuntu 16.04

The following 'errors' occur: 
requests 2.20.1 has requirement certifi>=2017.4.17, but you'll have certifi 2016.9.26 which is incompatible.
requests 2.20.1 has requirement chardet<3.1.0,>=3.0.2, but you'll have chardet 2.3.0 which is incompatible.

These errors were solved: by installing 'certifi' and 'chardet' and then running pip install upgrade cow.

Realize these are not really errors, but might be difficult to overcome if unfamiliar with pip.

**Comment by Bramvdhout** [comment]
Confirmed, happens to me too. Uninstalling and reinstalling certifi and chardet, then upgrade cow seems to have fixed it
