### ISSUE TITLE
Windows installation instructions

### ISSUE THREAD

**Issue by Bramvdhout** [CLARIAH/COW#66]
While installing COW on Windows, I ran into the following issues/deviations when compared to the instructions @ https://csvw-converter.readthedocs.io/en/latest/ 
It might be useful to split the installation instructions up between Windows and Mac.

-------

- It's important to create a COW folder and open command prompt in there.

- Terminal is not a windows term, replace it with Command Prompt (right-click on start and select command prompt or left-click start and type `cmd` and press enter).

- Source bin/activate doesn’t work, had to `cd Scripts` and then activate, and THEN go back to the main folder.

Also worth noting that there's no example CSV (imf_gdppc.csv) in the files anymore! I'd suggest including it again, or telling people to create it themselves (which I ended up doing).

**Comment by Bramvdhout** [comment]
If you don't create a COW folder, all the files and folders will just be thrown in your root. That's not really a problem but it's a lot less cluttered if they're in a folder. 

Agree with everything else. Thanks!

**Comment by melvinroest** [comment]
It doesn't seem this is an issue right now, if it comes up again, then I think it might be handy to add Windows installation instructions.
