### ISSUE TITLE
anyURI should also work for virtual columns

### ISSUE THREAD

**Issue by albertmeronyo** [CLARIAH/COW#67]

**Comment by rlzijdeman** [comment]
Thanks @albertmeronyo it works both in the 'regular' and 'virtual case'.
```<https://iisg.amsterdam/6> <http://www.w3.org/2004/02/skos/core#related> <https://adamlink.nl/geo/district/buurt-mm/109> <https://iisg.amsterdam/anyUri/assertion/e69b104d/2019-02-    12T13:54> .```
```<https://iisg.amsterdam/M> <http://www.w3.org/2002/07/owl#sameAs> <https://adamlink.nl/geo/district/buurt-m/132> <https://iisg.amsterdam/anyUri/assertion/e69b104d/2019-02-12T13:54    > .```
```ValueError: Expecting property name: line 117 column 2 (char 4042)```
