### ISSUE TITLE
Crash caused by server issues

### ISSUE THREAD

**Issue by RoderickvanderWeerdt** [CLARIAH/COW#72]
The URL used to locate the json template should be changed so it won't have to retrieve the JSON schema from the VU server anymore.
The template should be relocated to github.

**Comment by RoderickvanderWeerdt** [comment]
JSON template has been moved, but this issue will be kept open until the new url has been shortened using PURL.

**Comment by rijpma** [comment]
Would the json files that still have the old template location in them (e.g. https://github.com/CLARIAH/wp4-cow-conversions/blob/master/catasto/emigra.csv-metadata.json#L64) still break? That is, do we need to update those?

**Comment by albertmeronyo** [comment]
@rijpma Yes, we should update them. I can do that quickly in one pass once we have one final stable URL
