### ISSUE TITLE
what datatype to use for virtual column with prefixed URI

### ISSUE THREAD

**Issue by rlzijdeman** [CLARIAH/COW#74]
```
{
     "virtual": true,
     "propertyUrl": "rdf:type",
     "valueUrl": "schema:Person"
   },
```
For example, with ```"datatype": "xsd:anyURI"``` the above does not create a triple for each row.

**Comment by rijpma** [comment]
I'm not sure I understand the issue. Does datatype work at all when the valueUrl is already fixed to be a single URI?

Maybe you make a short example of the unexpected behaviour?
