### ISSUE TITLE
Encoding Issues on Build and Convert

### ISSUE THREAD

**Issue by raadjoe** [CLARIAH/COW#76]
Hi,

I'm trying to convert the file `locations.csv` attached below.
This file contains some special characters that are causing encoding issues when building and converting. This was not an issue in the previous version of COW in Python2.

When executing the command `cow_tool build locations.csv`, the function that detects the delimiter in `csvw.py` is causing the errors (no more errors when we set the delimiter manually).

When executing the command `cow_tool convert locations.csv`, the function `git_hash` in `_init_.py` is causing the errors (no more errors when we remove this function). 

[locations.csv.zip](https://github.com/CLARIAH/COW/files/3840481/locations.csv.zip)

**Comment by albertmeronyo** [comment]
Hi @raadjoe , thanks for reporting this. Should be fixed now; can you do 

```
$ pip install cow_csvw --upgrade
```

and confirm?
