### ISSUE TITLE
Python3 raises TypeError on Jinja template render()

### ISSUE THREAD

**Issue by albertmeronyo** [CLARIAH/COW#77]
After an extensive dive into the code, the core of the issue is that now Python 3 comparison operators (`<`, `>`, etc.) are datatype sensitive, while Python 2 would happily evaluate expressions like `'3' > 3`. This is no longer the case, so calls to Jinja to render templates fail if no datatype information is supplied with the context variables.

I'd be very surprised that this particular example ever worked correctly with the example file (instances of `iish:rich` would surely be created, but not following the logic of the template expression).

There is no simple workaround other than falling back to the Python2 version. The proper solution is to pass down a datatype data structure to `render_pattern()` and use it to cast to proper types before rendering the template.

**Comment by melvinroest** [comment]
Python 3 has more strict type checking when boolean comparisons are done. What needs to be done is casting in the right manner. I've updated the developer documentation with regards to this change from Python 2 to Python 3. 

We shouldn't want to emulate loose type checking, as it can lead to logical errors as well. For example: let's say you compare `some_number > 99`. `some_number` is a string here. Do you then mean to compare it alphabetically or numerically? Python 2 would assume an alphabetic comparison, no matter what you would actually want. However, by specifying the type of `some_number` or the literal value `99` (which would be `"99"` as a string value), you can decide what type of comparison you want.

For a practical example see: https://csvw-converter.readthedocs.io/en/latest/ --> question: I get `TypeError: '>' not supported between instances of 'int' and 'str'` when doing the convert step, what does that mean?

I'm closing this issue as I've also informed members of Clariah privately on this matter.
