### ISSUE TITLE
Templating conditional on other columns

### ISSUE THREAD

**Issue by RubenSchalk** [CLARIAH/COW#81]
In some (rare) cases it would be useful to make templating conditional on other columns. See example below, where the value of the column `value` should be included only if the column `prefix` takes the value 'SANR'

```{
  "datatype": "string",
  "virtual": true,
  "titles": [
     "value"
    ],
  "aboutUrl": "hdng:gemeente/{NAAM}",
  "propertyUrl": "hdng:dimension/SANR",
  "valueUrl": "hdng:code/SANR/{% if prefix == 'SANR' %}{{value}}{% endif %}",
  "dc:description": "Schoolarrondissementsnummer"
 },
```

**Comment by rijpma** [comment]
Is `"name": "prefix"` specified in your description of the "prefix" column? Small chance this already works if it does.

**Comment by RubenSchalk** [comment]
Thanks Auke! If I do it like this it seems to work:

```
{
  "datatype": "string",
  "virtual": true,
  "titles": [
   "suffix"
  ],
  "name": "suffix",
  "aboutUrl": "hdng:gemeente/{NAAM}",
  "propertyUrl": "hdng:vocab/SANR",
  "valueUrl": "hdng:code/SANR/{% if suffix == 'SANR' %}{{value}}{% endif %}",
  "dc:description": "Schoolarrondissementsnummer"
},
```
Generates: `<https://iisg.amsterdam/hdng/gemeente/SOMEREN> <https://iisg.amsterdam/hdng/vocab/SANR> <https://iisg.amsterdam/hdng/code/SANR/12>`
