### ISSUE TITLE
Skip rows

### ISSUE THREAD

**Issue by albertmeronyo** [CLARIAH/COW#82]
If a new keyword is detected (e.g. {{_null}} or {{_skip}}) in Jinja templates, skip the generation of triples for that row

**Comment by rlzijdeman** [comment]
to add: this used to work with option 'null' see the engineering documentation at: https://csvw-converter.readthedocs.io/en/latest/ (note: there is also user documentation at: https://github.com/clariah/cow/wiki )

**Comment by melvinroest** [comment]
I find this feature a bit difficult to understand. The `null` option allows for skipping columns. This feature asks about skipping rows, but why would you want to have that in a Jinja template? Jinja templates seem to be computed for columns, not for whole rows.

**Comment by RubenSchalk** [comment]
Can be closed. Related to a use case where the data was in long format, and a certain combination of SANR/value needed to be skipped both as `propertyURL` and as `cvsw:value`. But was solved.

`variable value`
`SANR  345`
`ETC 5678`  

solution:

`{`
    `"datatype": "integer",`
    `"virtual": true,`
    `"titles": ["suffix" ],`
    `"name": "suffix",`
    `"@id": "https://iisg.amsterdam/hdng_gemeenten.csv/column/suffix",`
    `"propertyUrl": "hdng:variable/{suffix}",`
   ` "dc:description": "variable code",`
   ` "csvw:value": "{% if suffix != 'SANR' %}{{value}}{% endif %}",`
   ` "null": {"@list": [{"name": "suffix", "null": ["SANR"]}]}`
  ` }`
