### ISSUE TITLE
Add option to CLI to generate gziped output

### ISSUE THREAD

**Issue by albertmeronyo** [CLARIAH/COW#86]
It would be nice for cow to produce gzipped output from the CLI:
```cow_tool convert my.csv --gz```

Currently serialization to a file is hard-coded, so this brings up the bigger issue of serializing to stdout instead, and then having a parameter to serialize to a (gzipped) file if needed

**Comment by melvinroest** [comment]
I'm keeping the issue open, but recommend dropping this feature from the backlog (not developing it at all). Developing a feature like this will take away time from the core development of CoW, which is converting CSVs to linked data. A second reason is that it violates the UNIX principle of command-line tools: do one thing well. In short, CoW shouldn't try too much if other tools are already perfect solutions for it, the documentation can always be expanded to explain how to use those tools.

Finally, there are a myriad of command-line tools and software solutions to gzip a CSV. It also doesn't take too long, as I gzipped a 3.5GB CSV file to 0.9GB within a matter of minutes.

**Comment by wxwilcke** [comment]
Hi Albert, Melvin;

To make this ability easily accessible for the less technical skilled user, I've implemented this function in the base COW branch. You can tell COW to produce gzipped output with the '--gzip' flag.

- Xander
