### ISSUE TITLE
"null" function not working with python 3

### ISSUE THREAD

**Issue by RubenSchalk** [CLARIAH/COW#88]
When using python 3, null values specified in the json file are not skipped. Instead, the block below results in this triple when the field of column "occupation" is empty in the csv:

`<https://iisg.amsterdam/openarchdeath/person/346537> <http://schema.org/hasOccupation> <https://iisg.amsterdam/openarchdeath/occupation/> `

  ```
 "virtual": "true",
       "datatype": "string",
       "name": "occupation",
       "propertyUrl": "schema:hasOccupation",
       "valueUrl": "occupation/{{occupation}}",
       "null": [""]
```
Note that the conversion works fine, it only shows in the .nq file. In python 2.7 no triples are generated in this instance, as it should be.

**Comment by Sozialarchiv** [comment]
I set the hole column to null. This worked for me with python 3.

```json
 "columns": [
      null,
      {
        "propertyUrl": "schema:givenName",
        "name": "First name"
      },
]
```

It would be nice if this part would be more clear in the documentation.
