### ISSUE TITLE
TypeError: write() argument must be str, not bytes

### ISSUE THREAD

**Issue by Sozialarchiv** [CLARIAH/COW#89]
I run the following command and got the following error

`cow_tool -f=turtle convert test.csv`

```
Traceback (most recent call last):
  File "cow_csvw\csvw_tool.py", line 50, in __init__
    output_file.write(g.serialize(format=output_format))

```

https://github.com/CLARIAH/COW/blob/master/src/csvw_tool.py#L50

The nq file was okay but the turtle file was empty.

I could fix it by adding decode to the line:

`output_file.write(g.serialize(format=output_format).decode())`

Windows 10 python 3.8

**Comment by wagonhelm** [comment]
I had to do this as well in Ubuntu 18.04

**Comment by melvinroest** [comment]
I reproduced the issue as well.
