### ISSUE TITLE
valueUrl with "if" and prefix not working

### ISSUE THREAD

**Issue by Sozialarchiv** [CLARIAH/COW#90]
if I use "valueUrl": "schema:Male" I will get `ns2:Male`

but if I use  "valueUrl": "{% if Gender == 'm' %}schema:Male{% endif %}" I will get `<https://baseUrl/schema:Male>`

**Comment by rlzijdeman** [comment]
Hi @Sozialarchiv, thank you very much for this and the other report. Currently, you have caught us off guard, as we are currently in the process of writing a Python3 only version of CoW, as some of the Python2 version functionality did work appropriately. This is to say, that we are really happy with your feedback, but it may take a bit longer to get back to it, as we will not try and fix the current version of CoW, but rather implement solutions to your issues in the new code base.

Best,

Richard

**Comment by rlzijdeman** [comment]
ps: @Sozialarchiv the current dev branch is: https://github.com/CLARIAH/COW/tree/2020

**Comment by Sozialarchiv** [comment]
Thank you. I build the 2020 version the issue is also there.

**Comment by melvinroest** [comment]
Given how the system is currently setup, this seems to be an enhancement. As I don't see how Jinja template strings would interpolate prefixes.

**Comment by rlzijdeman** [comment]
> Given how the system is currently set up, this seems to be an enhancement. As I don't see how Jinja template strings would interpolate prefixes, it's not what Jinja is made for.

Hi, I'm a bit more into again, and agree with @melvinroest: so far all our use cases were just about modding the part after the prefix, not for the prefix to be conditional. (e.g. use foaf:person for x and schema:person for y).
