### ISSUE TITLE
aboutUrl with ? not working

### ISSUE THREAD

**Issue by Sozialarchiv** [CLARIAH/COW#91]
`"aboutUrl": "?id={id}"` is not working

**Comment by melvinroest** [comment]
@Sozialarchiv this gives me a little bit too little of context.

So you observed that `"aboutUrl": "?id={id}"` is not working, but I'm now having the following questions:
* What happened? / how did it not work?
* What output were you expecting if it would work?

**Comment by rlzijdeman** [comment]
Hi @Sozialarchiv 

thanks for reporting. In the latest version, this issue is fixed. I tested with a variable called `Rank`. In my `-metadata.json` I wrote:

```
   {
    "virtual": true,
    "aboutUrl": "?id={Rank}",
    "valueUrl": "{Country}"
   },
```

which gives me as output:

```
<https://iisg.amsterdam/?id=6>
```

**Comment by Sozialarchiv** [comment]
Thank you very much.
