### ISSUE TITLE
Why does provenance urls starting with https://iisg.amsterdam/

### ISSUE THREAD

**Issue by Sozialarchiv** [CLARIAH/COW#94]
Why are all provenance URIs starting with https://iisg.amsterdam/... ? Would it no make more sense to use the base url or to give the  possiblity to define an url?

**Comment by rlzijdeman** [comment]
good point!

**Comment by melvinroest** [comment]
It just so happens that #100 contains a fix that fixes this issue as well. I managed to change all the provenance IRIs that had `https://iisg.amsterdam/` in it.
