### ISSUE TITLE
Overide @Base when creating subject URI

### ISSUE THREAD

**Issue by wagonhelm** [CLARIAH/COW#95]
One issue I am having troubles getting around is using a column of URI's which I will use as a Subject for many triples.  To try and do this my table schema looks as follows

"primaryKey": column_name
"aboutUrl": {column_name}

But what this ends up doing it concatenating my @base with my column_name value. i.e. https://base/column_value_uri

This same issue comes up when creating virtual columns with the subject being the value of this column.  Is there a workaround I can use for this so I can override creating a URI to not use the @base, or have a blank @base?

Many Thanks

**Comment by RubenSchalk** [comment]
@wagonhelm, thanks for reporting. Have you tried writing it like this:

```
{
       "virtual": "true",
       "aboutUrl":"{{column name}}",
       "propertyUrl": "vocab/instance", 
       "valueUrl": "{{column name}}"
     }, 
```
That should override the **@base**

**Comment by wagonhelm** [comment]
Unless I'm doing something wrong that does not seem to work for py2, py3 .nq or .ttl

**Comment by melvinroest** [comment]
@wagonhelm: could you see if this issue still persist with the new version? CoW has recently been updated.

**Comment by rlzijdeman** [comment]
@wagonhelm I've tested this and seems to work. Closing this issue. Please reopen if it still causes an issue on your side.
