### ISSUE TITLE
Variables not skipped when included to specify null in list

### ISSUE THREAD

**Issue by RubenSchalk** [CLARIAH/COW#98]
If variable `x` should not be included as a separate triple, but variable `x` is used in a `@list`to specify a `null` field for another variable, triples for `x` are still generated. 

Example:
```json
{
    "virtual": "true",
    "datatype": "date",
    "propertyUrl": "schema:birthDate",
    "dc:description": "Date of birth",
    "null": {"@list": [{"name": "Month_Birth", "null": "0"},
      {"name": "Day_Birth", "null": "0"}]},
    "csvw:value": "{{['%04d'| format(Year_Birth|int),'-','%02d' | format(Month_Birth|int),'-','%02d'|format(Day_Birth|int)]|join}}"
  }
```

This will still produce triples for both `Month_Birth` and `Day_Birth`, even when they are specified nowhere else in the metadata json.

**Comment by RubenSchalk** [comment]
Note: this also happens with Python 2

**Comment by melvinroest** [comment]
I see, so in this case, while `Month_Birth` and `_Day_Birth` are in the csv file, you don't want them converted to linked data. You want the combination of `YYYY-MM-DD`. 

So a MVE CSV would be:

```
Year_Birth,Month_Birth,Day_Birth
1990,6,29
1990,0,0
```

**Comment by melvinroest** [comment]
Closing this issue for now, if the patch in the `2020` branch doesn't work, then let's reopen it.
