### ISSUE TITLE
incorrect extension for prefix of schema.org

### ISSUE THREAD

**Issue by rlzijdeman** [CLARIAH/COW#99]
Let's ask the team for input re the prefixes list and fix any issues in one go

**Comment by rlzijdeman** [comment]
@melvinroest I see some more 'issues' with this file -> let's ask for input from the team and fix all issues in one go

**Comment by LvanWissen** [comment]
From https://schema.org/docs/faq.html#19 :

> **Q: Should we write 'https://schema.org' or 'http://schema.org' in our markup?**
> There is a general trend towards using 'https' more widely, and you can already write 'https://schema.org' in your structured data. Over time we will migrate the schema.org site itself towards using https: as the default version of the site and our preferred form in examples. However 'http://schema.org' -based URLs in structured data markup will remain widely understood for the forseeable future and there should be no urgency about migrating existing data. This is a lengthy way of saying that both 'https://schema.org' and 'http://schema.org' are fine.

Though I'm in favour of the HTTPS Everywhere movement, it doesn't help if one dataset has <<http://schema.org/Person>> resources and another <<https://schema.org/Person>>.

**Comment by rlzijdeman** [comment]
Hi @LvanWissen I thought I had changed this issue entirely, as (1) I indeed was glad to see that `http` was still valid afterall, but the issue also was more about our list of prefixes. so closing this now, and created a prefix #101 (pun intended)
